build:
	gcc crypto.c -o crypto
	javac Stocks.java
	g++ valley.cpp -o valley
	g++ ridge.cpp -o ridge

run-p1:
	./crypto

run-p2:
	java Stocks

run-p3:
	./valley

run-p4:
	./ridge

clean:
	rm -f crypto *.class valley ridge
